-- AP Control — PostgreSQL schema (cloud / Neon target).
-- Mirrors src/db/schema.sql (SQLite) with Postgres dialect:
--   * INTEGER PRIMARY KEY AUTOINCREMENT  -> GENERATED BY DEFAULT AS IDENTITY
--   * money columns are BIGINT agorot (64-bit, matches SQLite INTEGER)
--   * timestamp defaults use to_char(now()) to keep the 'YYYY-MM-DD HH:MM:SS' text format
--   * tables are ordered so every FK target exists first (Postgres validates FKs at create time)
-- Amounts are agorot; dates 'YYYY-MM-DD'; timestamps 'YYYY-MM-DD HH:MM:SS' (UTC).

-- companies ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS companies (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name         TEXT NOT NULL,
  company_type TEXT,
  tax_id       TEXT
);

-- users -------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS users (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name          TEXT NOT NULL,
  role          TEXT NOT NULL CHECK (role IN ('owner','secretary')),
  username      TEXT,
  email         TEXT,
  password_hash TEXT
);
ALTER TABLE users ADD COLUMN IF NOT EXISTS email TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS label TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS permissions TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS phone TEXT;
CREATE UNIQUE INDEX IF NOT EXISTS ux_users_username ON users(username) WHERE username IS NOT NULL;

-- Per-user company access (הפרדת חברות). Non-owner sees ONLY listed companies; owner sees all.
CREATE TABLE IF NOT EXISTS user_companies (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  company_id INTEGER NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  UNIQUE (user_id, company_id)
);

-- Password-reset tokens (email flow). Only a SHA-256 hash of the token is stored.
CREATE TABLE IF NOT EXISTS password_resets (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    INTEGER NOT NULL REFERENCES users(id),
  token_hash TEXT NOT NULL,
  expires_at TEXT NOT NULL,
  used_at    TEXT
);
CREATE INDEX IF NOT EXISTS ix_password_resets_token ON password_resets(token_hash);

-- Calendar events / reminders for the "יומן" page.
CREATE TABLE IF NOT EXISTS calendar_events (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title       TEXT NOT NULL,
  event_date  TEXT NOT NULL,
  event_time  TEXT,
  remind      INTEGER NOT NULL DEFAULT 0,
  remind_sent INTEGER NOT NULL DEFAULT 0,
  created_by  INTEGER REFERENCES users(id)
);
CREATE INDEX IF NOT EXISTS ix_calendar_events_date ON calendar_events(event_date);

-- Approval workflow: edits by non-owners queued for the owner.
CREATE TABLE IF NOT EXISTS change_requests (
  id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  requested_by      INTEGER REFERENCES users(id),
  requested_by_name TEXT,
  action            TEXT NOT NULL,
  entity_type       TEXT,
  entity_id         INTEGER,
  payload           TEXT NOT NULL,
  summary           TEXT,
  status            TEXT NOT NULL DEFAULT 'pending',
  decided_by        INTEGER,
  decided_at        TEXT,
  decision_note     TEXT,
  result_summary    TEXT,
  created_at        TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS ix_change_requests_status ON change_requests(status);

-- stores ------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS stores (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id INTEGER NOT NULL REFERENCES companies(id),
  name       TEXT NOT NULL,
  address    TEXT
);

-- bank_accounts — 1:1 with a store ----------------------------------------------
CREATE TABLE IF NOT EXISTS bank_accounts (
  id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id     INTEGER NOT NULL REFERENCES companies(id),
  store_id       INTEGER NOT NULL UNIQUE REFERENCES stores(id),
  bank_name      TEXT NOT NULL DEFAULT 'הפועלים',
  branch         TEXT NOT NULL,
  account_number TEXT NOT NULL,
  display_name   TEXT NOT NULL
);

-- suppliers ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS suppliers (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        TEXT NOT NULL,
  tax_id      TEXT,
  status      TEXT NOT NULL DEFAULT 'pending'
              CHECK (status IN ('pending','approved','blocked')),
  approved_by INTEGER REFERENCES users(id),
  approved_at TEXT,
  notes       TEXT,
  phone          TEXT,
  email          TEXT,
  contact_name   TEXT,
  contact_phone  TEXT
);

-- invoices ----------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS invoices (
  id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  supplier_id        INTEGER NOT NULL REFERENCES suppliers(id),
  company_id         INTEGER NOT NULL REFERENCES companies(id),
  store_id           INTEGER NOT NULL REFERENCES stores(id),
  bank_account_id    INTEGER REFERENCES bank_accounts(id),
  invoice_number     TEXT NOT NULL,
  allocation_number  TEXT,
  invoice_date       TEXT NOT NULL,
  amount_before_vat  BIGINT NOT NULL,
  vat_amount         BIGINT NOT NULL DEFAULT 0,
  total_amount       BIGINT NOT NULL,
  doc_type           TEXT NOT NULL
                     CHECK (doc_type IN ('tax_invoice','tax_invoice_receipt','credit_note')),
  image_path         TEXT,
  status             TEXT NOT NULL DEFAULT 'recorded'
                     CHECK (status IN ('recorded','approved_for_payment','on_hold','paid')),
  hold_reason        TEXT,
  created_by         INTEGER NOT NULL REFERENCES users(id),
  created_at         TEXT NOT NULL DEFAULT to_char(now(), 'YYYY-MM-DD HH24:MI:SS')
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_invoices_allocation
  ON invoices(allocation_number) WHERE allocation_number IS NOT NULL;
CREATE INDEX IF NOT EXISTS ix_invoices_supplier_number
  ON invoices(supplier_id, invoice_number);

-- payments ----------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS payments (
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bank_account_id INTEGER NOT NULL REFERENCES bank_accounts(id),
  method          TEXT NOT NULL DEFAULT 'check'
                  CHECK (method IN ('check','cash','credit','transfer','batch')),
  check_number    TEXT,
  reference       TEXT,
  payer_name      TEXT,
  card_last4      TEXT,
  batch_number    TEXT,
  payment_date    TEXT NOT NULL,
  amount          BIGINT NOT NULL,
  status          TEXT NOT NULL DEFAULT 'issued'
                  CHECK (status IN ('issued','cleared','voided')),
  cleared_date    TEXT,
  created_by      INTEGER NOT NULL REFERENCES users(id),
  created_at      TEXT NOT NULL DEFAULT to_char(now(), 'YYYY-MM-DD HH24:MI:SS')
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_payments_account_check
  ON payments(bank_account_id, check_number) WHERE check_number IS NOT NULL;

-- payment_lines -----------------------------------------------------------------
CREATE TABLE IF NOT EXISTS payment_lines (
  id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  payment_id     INTEGER NOT NULL REFERENCES payments(id) ON DELETE CASCADE,
  invoice_id     INTEGER NOT NULL REFERENCES invoices(id),
  amount_applied BIGINT NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_payment_lines_invoice
  ON payment_lines(payment_id, invoice_id);

-- bank_transactions -------------------------------------------------------------
CREATE TABLE IF NOT EXISTS bank_transactions (
  id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bank_account_id    INTEGER NOT NULL REFERENCES bank_accounts(id),
  txn_date           TEXT NOT NULL,
  amount             BIGINT NOT NULL,
  description        TEXT,
  raw_reference      TEXT,
  balance_after      BIGINT,
  source             TEXT NOT NULL DEFAULT 'scraper',
  matched_payment_id INTEGER REFERENCES payments(id)
);
ALTER TABLE bank_transactions ADD COLUMN IF NOT EXISTS balance_after BIGINT;

-- invoice_ocr -------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS invoice_ocr (
  invoice_id INTEGER PRIMARY KEY REFERENCES invoices(id) ON DELETE CASCADE,
  raw_text   TEXT,
  extracted  TEXT,
  provider   TEXT,
  ran_at     TEXT NOT NULL DEFAULT to_char(now(), 'YYYY-MM-DD HH24:MI:SS')
);

-- z_reports ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS z_reports (
  id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  store_id         INTEGER NOT NULL REFERENCES stores(id),
  z_number         TEXT NOT NULL,
  z_date           TEXT NOT NULL,
  daily_total      BIGINT NOT NULL DEFAULT 0,
  drawer_cash      BIGINT NOT NULL DEFAULT 0,
  drawer_check     BIGINT NOT NULL DEFAULT 0,
  drawer_credit    BIGINT NOT NULL DEFAULT 0,
  drawer_hakafa    BIGINT NOT NULL DEFAULT 0,
  drawer_vouchers  BIGINT NOT NULL DEFAULT 0,
  drawer_total     BIGINT NOT NULL DEFAULT 0,
  deposit_amount   BIGINT,
  deposit_bag      TEXT,
  deposit_breakdown TEXT,
  cc_kal BIGINT, cc_isracard BIGINT, cc_diners BIGINT, cc_amex BIGINT,
  cc_general BIGINT, cc_tourist BIGINT, cc_total BIGINT,
  status           TEXT NOT NULL DEFAULT 'ok' CHECK (status IN ('ok','unmatched')),
  reconcile_notes  TEXT,
  created_by       INTEGER NOT NULL REFERENCES users(id),
  created_at       TEXT NOT NULL DEFAULT to_char(now(), 'YYYY-MM-DD HH24:MI:SS')
);
CREATE INDEX IF NOT EXISTS ix_zreports_store_date ON z_reports(store_id, z_date);

-- z_expenses --------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS z_expenses (
  id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  z_report_id      INTEGER NOT NULL REFERENCES z_reports(id) ON DELETE CASCADE,
  expense_date     TEXT,
  payer_name       TEXT,
  description_type TEXT,
  employee_name    TEXT,
  amount           BIGINT NOT NULL DEFAULT 0,
  image_path       TEXT,
  created_at       TEXT NOT NULL DEFAULT to_char(now(), 'YYYY-MM-DD HH24:MI:SS')
);

-- sales_entries -----------------------------------------------------------------
CREATE TABLE IF NOT EXISTS sales_entries (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  store_id   INTEGER NOT NULL REFERENCES stores(id),
  sale_date  TEXT NOT NULL,
  amount     BIGINT NOT NULL,
  notes      TEXT,
  created_by INTEGER NOT NULL REFERENCES users(id),
  created_at TEXT NOT NULL DEFAULT to_char(now(), 'YYYY-MM-DD HH24:MI:SS')
);
CREATE INDEX IF NOT EXISTS ix_sales_store_date ON sales_entries(store_id, sale_date);

-- audit_log ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS audit_log (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     INTEGER REFERENCES users(id),
  action      TEXT NOT NULL,
  entity_type TEXT NOT NULL,
  entity_id   INTEGER,
  timestamp   TEXT NOT NULL DEFAULT to_char(now(), 'YYYY-MM-DD HH24:MI:SS'),
  details     TEXT
);
